# Copyright 2017 Sean Kelleher. All rights reserved.
# Use of this source code is governed by a BSD
# licence that can be found in the LICENCE file.

TARGET: print.o
	BUILD_LIB

%.o: %.c
	gcc -c -I. -o $@ $<
